/* 2010-11-29: File added by Sony Corporation */
/*
 * PARTNER-Jet Linux support patch by KMC
 *
 * Ver2.0	08.04.14
 *
 */





asm("	.text");
asm("	.align	2");
asm("	.global	__kmc_code_data");
asm("__kmc_code_data:");
asm("	la	$5, __kmc_code_data_table");
asm("	li	$6, 4");
asm("	rol	$4, $4, 3");
asm("	andi	$7, $4, 0x7f8");
asm("loop:");
asm("	addu	$7, $7, $5");
asm("	jr	$7");
asm("__kmc_code_data_table:");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");

asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");

asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");

asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");

asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");

asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");

asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");

asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");

asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");

asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");

asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");

asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");

asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");

asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");

asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");
asm("	addiu	$6, $6, -1");
asm("	beq	$0,$0,jmp_end");

asm("jmp_end:");
asm("	ror	$4, $4, 8");
asm("	andi	$7, $4, 0x7f8");
asm("	bne	$6, $0, loop");
asm("	jr	$31");



