obj-y					:= main.o memmap.o image.o pgbmp.o
obj-y					+= exreg.o proc.o
obj-y					+= optimizer/
obj-$(CONFIG_SNSC_SSBOOT_PAGE_STAT)	+= pgstat.o
obj-$(CONFIG_SNSC_SSBOOT_PAGE_ATTR_DUMP)	+= page_attr_dump.o
obj-$(CONFIG_SNSC_SSBOOT_SBI)		+= sbi.o
obj-$(CONFIG_SNSC_SSBOOT_SBI_FILE)	+= sbi_file.o
